services:
 app:
   build:
     context: .
     dockerfile: Dockerfile
   ports:
     - "8501:8501"
   volumes:
     - ./app:/app
   environment:
     - OLLAMA_HOST=host.docker.internal

 ollama:
   image: ollama/ollama
   ports:
     - "11434:11434"
   volumes:
     - ollama-data:/root/.ollama

volumes:
 ollama-data: